# Generated by Django 4.1.2 on 2022-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(help_text='Enter the number.'),
        ),
    ]
