# Generated by Django 4.1.2 on 2022-11-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publishing_house',
            new_name='publishing',
        ),
    ]
