# Generated by Django 4.1.2 on 2022-10-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0002_alter_author_id_alter_genre_id_alter_publishing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='logo',
            field=models.ImageField(default='qwer', upload_to='uploads/%Y/%m/%d/', verbose_name='Group logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Group name'),
        ),
    ]
