# Generated by Django 4.1.2 on 2022-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0003_author_logo_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='logo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Author'),
        ),
    ]
